# Automated Deployment via GitHub actions
# Required secrets:
name: Deploy DashEngine to Cloud Run
on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    # Check out master branch
     - name: Checkout
       uses: actions/checkout@master
    # Authenticate with GCP
     - name: GCP Authentication
       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
       with:
         version: '275.0.0'
         service_account_key: ${{ secrets.GCLOUD_AUTH }}
    # Build the Docker image
     - name: Build
       run: |        
         gcloud builds submit \\
            --project ${{ secrets.GCLOUD_PROJECT }} \\
            --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} \\
            .
    # Deploy to Cloud Run
     - name: Deploy
       run: |
         gcloud run deploy ${{ secrets.GCLOUD_APP_NAME }} \\
         --quiet \\
         --platform managed \\
         --allow-unauthenticated \\
         --region europe-west1 \\
         --project ${{ secrets.GCLOUD_PROJECT }} \\
         --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
