# Automated Deployment via GitHub actions
# Required secrets:
#  GCLOUD_REGION:       GCP Region for deployment (e.g europe-west1)
#  GCLOUD_PROJECT:      GCP Project ID for the target project 
#  GCLOUD_APP_NAME:     Name of the target Cloud Run Application
name: Cloud Run Deployment
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    # Check out master branch
     - name: Checkout
       uses: actions/checkout@master
    # Authenticate to GCP 
     - name: Authenticate
       uses: 'google-github-actions/auth@v1'
       with:
         workload_identity_provider: 'projects/786649440348/locations/global/workloadIdentityPools/wip-pool/providers/wip-provider'
         service_account: 'github-actions@${{ secrets.GCLOUD_PROJECT }}.iam.gserviceaccount.com'    
    # Install gcloud sdk
     - name: Set up Cloud SDK
       uses: google-github-actions/setup-gcloud@v0
    # Build the Docker image
     - name: Build
       run: >
         gcloud builds submit .
         --project ${{ secrets.GCLOUD_PROJECT }}
         --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
    # Deploy to Cloud Run
     - name: Deploy
       run: >
         gcloud run deploy ${{ secrets.GCLOUD_APP_NAME }} 
         --quiet 
         --platform managed 
         --allow-unauthenticated 
         --region ${{ secrets.GCLOUD_REGION }}
         --project ${{ secrets.GCLOUD_PROJECT }} 
         --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
         --memory 2Gi
         --max-instances 1 
